server:
  port: 8080

spring:
  application:
     name: Apigateway
  cloud:
    gateway:
      routes:
      - id: Profile
        uri: http://localhost:8081/
        predicates:
        - Path=/profile/**
        
      - id: Product
        uri: http://localhost:8082/
        predicates:
        - Path=/product/**
        
        - id: Order
        uri: http://localhost:8083/
        predicates:
        - Path=/order/**
